# OG Web.site Unit 3 - NumPy ndarray Evidence

This notebook is the evidence for Q3: use the third-party library NumPy to create and save an ndarray. The markdown and comments explain how the ndarray is created and saved.


## What this evidence proves

- NumPy is imported as a third-party library.
- A two-dimensional ndarray is created.
- The ndarray properties are printed.
- The ndarray is saved as `.txt`, `.csv` and `.npy`.
- The saved files are loaded back to prove they work.


In [1]:
# Import the third-party NumPy library.
import numpy as np

# Create a two-dimensional ndarray from a nested list.
# Each inner list becomes one row. dtype=int stores the values as integers.
og_scores = np.array([[82, 76, 91], [68, 88, 95]], dtype=int)

# Print the ndarray and its properties as evidence.
print("Created ndarray:")
print(og_scores)
print("Shape:", og_scores.shape)
print("Dimensions:", og_scores.ndim)
print("Size:", og_scores.size)
print("Data type:", og_scores.dtype)


Created ndarray:
[[82 76 91]
 [68 88 95]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int32


## Saving the ndarray

`np.savetxt` saves the ndarray in a readable text or CSV-style format. `np.save` saves the ndarray in NumPy native `.npy` format so it can be loaded back later with the same structure.


In [2]:
# Save the ndarray as a comma-separated text file.
np.savetxt("og_unit3_scores_ndarray.txt", og_scores, fmt="%d", delimiter=",")

# Save the ndarray as a CSV-style evidence file.
np.savetxt("og_unit3_scores_ndarray.csv", og_scores, fmt="%d", delimiter=",")

# Save the ndarray in NumPy native .npy format.
np.save("og_unit3_scores_ndarray.npy", og_scores)

print("Saved files:")
print("og_unit3_scores_ndarray.txt")
print("og_unit3_scores_ndarray.csv")
print("og_unit3_scores_ndarray.npy")


Saved files:
og_unit3_scores_ndarray.txt
og_unit3_scores_ndarray.csv
og_unit3_scores_ndarray.npy


In [3]:
# Load the saved files back into Python to prove the save worked.
loaded_from_text = np.loadtxt("og_unit3_scores_ndarray.txt", delimiter=",", dtype=int)
loaded_from_npy = np.load("og_unit3_scores_ndarray.npy")

print("Loaded from text file:")
print(loaded_from_text)
print("Loaded from .npy file:")
print(loaded_from_npy)


Loaded from text file:
[[82 76 91]
 [68 88 95]]
Loaded from .npy file:
[[82 76 91]
 [68 88 95]]
