# Unit 3 Assessment 3 - NumPy ndarray Evidence

This notebook shows how I used the third-party library NumPy to create, check, save and reload an ndarray. The markdown and comments explain how the ndarray is created and saved.

In [1]:
# Import the third-party NumPy library.
# NumPy is used to create and work with ndarray objects.
import numpy as np

In [2]:
# Create a two-dimensional ndarray from a nested Python list.
# Each inner list becomes one row in the ndarray.
# dtype=int stores the values as integers.
og_scores = np.array([
    [82, 76, 91],
    [68, 88, 95]
], dtype=int)

print("Created ndarray:")
print(og_scores)

Created ndarray:
[[82 76 91]
 [68 88 95]]


In [3]:
# Check the ndarray properties.
# shape shows rows and columns.
# ndim shows the number of dimensions.
# size shows the total number of values.
# dtype shows the data type stored in the ndarray.
print("Shape:", og_scores.shape)
print("Dimensions:", og_scores.ndim)
print("Size:", og_scores.size)
print("Data type:", og_scores.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


In [4]:
# Save the ndarray as a readable text file.
np.savetxt("og_unit3_scores_ndarray.txt", og_scores, fmt="%d", delimiter=",")

# Save the ndarray as a CSV file.
np.savetxt("og_unit3_scores_ndarray.csv", og_scores, fmt="%d", delimiter=",")

# Save the ndarray in NumPy native .npy format.
np.save("og_unit3_scores_ndarray.npy", og_scores)

print("Saved ndarray files:")
print("og_unit3_scores_ndarray.txt")
print("og_unit3_scores_ndarray.csv")
print("og_unit3_scores_ndarray.npy")

Saved ndarray files:
og_unit3_scores_ndarray.txt
og_unit3_scores_ndarray.csv
og_unit3_scores_ndarray.npy


In [5]:
# Load the saved files back into Python.
# This proves that the ndarray was saved correctly.
loaded_txt = np.loadtxt("og_unit3_scores_ndarray.txt", delimiter=",", dtype=int)
loaded_csv = np.loadtxt("og_unit3_scores_ndarray.csv", delimiter=",", dtype=int)
loaded_npy = np.load("og_unit3_scores_ndarray.npy")

print("Loaded from TXT:")
print(loaded_txt)

print("Loaded from CSV:")
print(loaded_csv)

print("Loaded from NPY:")
print(loaded_npy)

Loaded from TXT:
[[82 76 91]
 [68 88 95]]
Loaded from CSV:
[[82 76 91]
 [68 88 95]]
Loaded from NPY:
[[82 76 91]
 [68 88 95]]


## Evidence summary

This notebook imports NumPy, creates a two-dimensional ndarray, checks the ndarray properties, saves it as TXT, CSV and NPY files, then loads the saved files back into Python to prove that the save process worked.