# Manipulating ndarrays

## Example 1 - arithmetic
You can add, subtract, multiply and divide ndarrays element-wise.  **"element-wise"** refers to performing operations between corresponding elements of two arrays. When you perform element-wise operations on two arrays of the same shape, the operation is applied independently to each pair of elements at the same position in the arrays.

In [1]:
import numpy as np

# Create two ndarrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
result_add = arr1 + arr2

# Element-wise subtraction
result_sub = arr1 - arr2

# Element-wise multiplication
result_mul = arr1 * arr2

# Element-wise division
result_div = arr1 / arr2

print("Addition:")
print(result_add)
print("\nSubtraction:")
print(result_sub)
print("\nMultiplication:")
print(result_mul)
print("\nDivision:")
print(result_div)

Addition:
[[ 6  8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## Example 2 - slicing
**Slicing** is the process of extracting specific parts of an array. In this example, we have a 2D array (arr) representing a matrix. We demonstrate three types of slicing:

* Extracting a row: We select the second row of the array using arr[1, :], where 1 represents the index of the second row and : means selecting all columns.
* Extracting a column: We select the second column of the array using arr[:, 1], where : means selecting all rows and 1 represents the index of the second column.
* Extracting a sub-array: We select the first two rows and the last two columns of the array using arr[:2, 1:], which selects the first two rows (:2) and columns starting from the second column (1:).

In [2]:
import numpy as np

# Create an ndarray
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing
# Extracting the second row
row = arr[1, :]
print("Second row:")
print(row)

# Extracting the second column
column = arr[:, 1]
print("\nSecond column:")
print(column)

# Extracting a sub-array
sub_arr = arr[:2, 1:]
print("\nSub-array:")
print(sub_arr)

Second row:
[4 5 6]

Second column:
[2 5 8]

Sub-array:
[[2 3]
 [5 6]]


## Example 3 - reshaping 

**Reshaping** involves changing the shape of an array while maintaining the total number of elements. In this example, we have a 1D array (arr) containing six elements. We reshape it into a 2x3 matrix using *arr.reshape(2, 3)*. This converts the 1D array into a 2D array with 2 rows and 3 columns.

In [7]:
import numpy as np

# Create a 1D ndarray
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ", arr)

# Reshape to a 2x3 array
reshaped_arr = arr.reshape(2, 3)
print("\nReshaped array:")
print(reshaped_arr)

Original array:  [1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


## Example 4 - splitting

**Splitting** involves dividing an array into multiple smaller arrays. We demonstrate two types of splitting:

* Horizontal split: We horizontally split an array (arr) into two equal parts using np.hsplit(arr, 2). This splits the array into two arrays of equal width along the horizontal axis.
* Vertical split: We vertically split an array (arr) into two equal parts using np.vsplit(arr, 2). This splits the array into two arrays of equal height along the vertical axis.

Each of these operations is common in data manipulation tasks and provides flexibility in handling arrays of different shapes and sizes.

In [9]:
import numpy as np

# Create an ndarray
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Split horizontally
split_arr_h = np.hsplit(arr, 2)
print("Split horizontally:")
print(split_arr_h)

# Split vertically
split_arr_v = np.vsplit(arr, 2)
print("\nSplit vertically:")
print(split_arr_v)

Split horizontally:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

Split vertically:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
