# How to create and save a NumPy ndarray
You can **create** NumPy ndarrays using *np.ndarray(shape=(2, 3), dtype=float)*.  You can specify the shape and data type and also either ask the user to input data or create it with initial data.

You can **save** NumPy ndarrays to disk in various formats, such as text files, binary files, or NumPy's native .npy format. NumPy provides functions like *numpy.savetxt()* and *numpy.save()* for saving ndarrays.

This demonstrates how you can create NumPy arrays using the *numpy.ndarray* class within a Jupyter Notebook environment. However, for most use cases, it's more common to use other NumPy array creation functions, such as *numpy.array()*, as they offer simpler syntax and handle common use cases more intuitively.

**You can see the files saved by browsing to https://jupyter.org/try-jupyter/tree/**

## ndarray example 1

In [1]:
# Import third-party NumPy library
import numpy as np

# Create an ndarray with a specified shape and data type
my_array = np.ndarray(shape=(2, 3), dtype=float)

# Let's output the contents of the empty array
print("Empty ndarray:")
print(my_array)

Empty ndarray:
[[1.54775658e-307 7.24647982e-308 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


## ndarray example 2

In [2]:
# Import third-party NumPy library
import numpy as np

# You can create an ndarray with initial data
data = [[1, 2, 3], [4, 5, 6]]
my_array_with_data = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array(data))
print("\nndarray with initial data:")
print(my_array_with_data)

# Saving ndarray to a text file, browse to https://jupyter.org/try-jupyter/tree/ to see your file
np.savetxt('my_array_with_data.txt', my_array_with_data)

# Loading array from text file
loaded_array_txt = np.loadtxt('my_array_with_data.txt')


ndarray with initial data:
[[1 2 3]
 [4 5 6]]


## ndarray example 3

In [3]:
# Import third-party NumPy library
import numpy as np

# Create an ndarray with a specified shape and data type
array3 = np.ndarray(shape=(5), dtype=int)

# Output the ndarray's size, shape, dimension and data type
print("Size :", array3.size)
print("Shape :", array3.shape)
print("Dimension :", array3.ndim)
print("Dataype :", array3.dtype)

# Saving ndarray to a text file, browse to https://jupyter.org/try-jupyter/tree/ to see your file
np.savetxt('my_array3.txt', array3)

# Loading array from text file
loaded_array3_txt = np.loadtxt('my_array3.txt')

Size : 5
Shape : (5,)
Dimension : 1
Dataype : int32


## ndarray example 4

In [4]:
import pandas as pd 
import numpy as np 
  
# create a dummy array 
data = [[1, 2, 3], [4, 5, 6]]
array4 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array(data))
print(array4) 
  
# convert array into dataframe 
DF = pd.DataFrame(array4) 
  
# save the dataframe as a csv file 
DF.to_csv("array4.csv")

[[1 2 3]
 [4 5 6]]
