# Unit 3 Assessment 3 Q3 - NumPy ndarray Practical Evidence

This notebook is the submission evidence for Q3: **Use the third-party library NumPy to create and save an ndarray**. It includes markdown explanations and code comments so the assessor can see how the ndarray is created and saved.

Assessment links covered: Unit J/650/0758 4.1, 4.3 and explanation requirement 3.3.


## What this evidence shows

- NumPy is imported as a third-party Python library.
- A two-dimensional ndarray is created from project-style score data.
- The ndarray shape, dimensions, size and data type are printed.
- The ndarray is saved as a text/CSV-style file using `np.savetxt`.
- The ndarray is saved in NumPy native format using `np.save`.
- The saved files are loaded back to prove the save worked.


In [1]:
# Import the third-party NumPy library.
# NumPy is used because it provides ndarray objects for numerical data.
import numpy as np

# Create a two-dimensional ndarray from a nested Python list.
# Each inner list becomes one row, so this creates 2 rows and 3 columns.
# dtype=int ensures the values are stored as integers.
og_scores = np.array([[82, 76, 91], [68, 88, 95]], dtype=int)

# Print the ndarray and its properties as evidence.
print("Created ndarray:")
print(og_scores)
print("Shape:", og_scores.shape)
print("Dimensions:", og_scores.ndim)
print("Size:", og_scores.size)
print("Data type:", og_scores.dtype)


Created ndarray:
[[82 76 91]
 [68 88 95]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int32


## Saving the ndarray

An ndarray can be saved so the data is not only temporary output in the notebook. `np.savetxt` saves the array in a readable text/CSV-style format. `np.save` saves the array in NumPy native `.npy` format, which preserves the ndarray structure and data type for later loading.


In [2]:
# Save the ndarray as a comma-separated text file.
# This format can be opened and checked as plain text.
np.savetxt("og_unit3_scores_ndarray.txt", og_scores, fmt="%d", delimiter=",")

# Save the same ndarray in NumPy native binary format.
# The .npy file is useful when the array needs to be loaded back into Python later.
np.save("og_unit3_scores_ndarray.npy", og_scores)

# Save a CSV-style copy as an extra readable evidence file.
np.savetxt("og_unit3_scores_ndarray.csv", og_scores, fmt="%d", delimiter=",")

print("Saved files:")
print("og_unit3_scores_ndarray.txt")
print("og_unit3_scores_ndarray.npy")
print("og_unit3_scores_ndarray.csv")


Saved files:
og_unit3_scores_ndarray.txt
og_unit3_scores_ndarray.npy
og_unit3_scores_ndarray.csv


In [3]:
# Load the saved files back into Python to prove the ndarray was saved correctly.
loaded_from_text = np.loadtxt("og_unit3_scores_ndarray.txt", delimiter=",", dtype=int)
loaded_from_npy = np.load("og_unit3_scores_ndarray.npy")

print("Loaded from text file:")
print(loaded_from_text)
print("Loaded from .npy file:")
print(loaded_from_npy)


Loaded from text file:
[[82 76 91]
 [68 88 95]]
Loaded from .npy file:
[[82 76 91]
 [68 88 95]]


## Evidence conclusion

This notebook shows the required practical process: NumPy is imported, an ndarray is created, the ndarray properties are inspected, the ndarray is saved to files, and the saved files are loaded back to prove the save worked. The comments and markdown explain each step for the assessor.
